#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")"

for file in .spacemacs .vimrc .tmux.conf ; do
  if [[ ! -s "$HOME/$file" ]]; then
    ln -s "$PWD/$file" "$HOME/$file"
  fi
done

mkdir -p "$HOME/bin/completions"

if [[ ! -e "$HOME/.emacs.d" ]]; then
  git clone --recursive https://github.com/syl20bnr/spacemacs "$HOME/.emacs.d"
fi
